//
//  RegisterFCMTokenUseCase.swift
//  KNUTICE
//
//  Created by 이정훈 on 10/31/25.
//

import Factory
import KNUtility

public protocol RegisterFCMTokenUseCase: Actor {
    /// Registers the provided FCM token with the KNUTICE server and persists it locally.
    ///
    /// - Parameter token: The FCM token string generated by Firebase.
    /// - Throws:
    ///   - `CancellationError` if the task is cancelled before completion.
    ///   - An error if the server registration fails.
    func execute(token: String) async throws
}

public actor RegisterFCMTokenUseCaseImpl: RegisterFCMTokenUseCase {
    @Injected(\.tokenRepository) private var repository
    
    /// Executes the token registration workflow.
    ///
    /// The workflow consists of the following steps:
    /// 1. Verifies if the current task has been cancelled.
    /// 2. Sends the token to the KNUTICE server via the repository.
    /// 3. Upon successful server registration, saves the token to the secure Keychain.
    ///
    /// - Parameter token: The FCM token to be registered.
    /// - Throws: Any error encountered during the repository registration process.
    public func execute(token: String) async throws {
        try Task.checkCancellation()
        
        // KNUTICE 서버에 저장된 토큰을 Keychain에 저장
        await FCMTokenKeychainManager.shared.save(fcmToken: token)
        
        // KNUTICE 서버에 토큰 업로드
        try await repository.register()
    }
}
